export const API_LIST = [
  { label: 'Authenticate Client', key: 1 },
  { label: 'Authenticate User', key: 2 },
  { label: 'Verify OTP', key: 3 },
  { label: 'Renew Access Token', key: 4 },
  { label: 'Device Registration', key: 5 },
  { label: 'List Registered Devices', key: 6 },
  { label: 'Delete Device', key: 7 },
  { label: 'Get Pending Authorisation Request', key: 8 },
  { label: 'Authorise a Pending Request', key: 9 },
  { label: 'Cancel a Pending Authorisation Request', key: 10 },
  { label: 'Users Profile', key: 11 },
  { label: 'Get Device Registration Settings', key: 12 },
  { label: 'Generate QR Code', key: 13 },
  { label: 'Verify QR Code', key: 14 },
  { label: 'Register Device for Push Notification', key: 15 },
  { label: 'Delete Device for Push Notification', key: 16 },
];
